//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `SmartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome.Interfaces;

/** @hidden */
public class _DetectorPrxI extends com.zeroc.Ice._ObjectPrxI implements SmartHome.Interfaces.DetectorPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
