//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `SmartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome.Detectors;

/** @hidden */
public class _MoveDetectorPrxI extends com.zeroc.Ice._ObjectPrxI implements SmartHome.Detectors.MoveDetectorPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
