//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `SmartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome.Detectors;

public interface MoveDetector extends SmartHome.Interfaces.SmartDevice,
                                      SmartHome.Interfaces.Detector
{
    boolean motionDetected(com.zeroc.Ice.Current current)
        throws SmartHome.Errors.ActionNotPermitted;

    void activateAlarm(com.zeroc.Ice.Current current)
        throws SmartHome.Errors.ActionNotPermitted;

    void deactivateAlarm(com.zeroc.Ice.Current current)
        throws SmartHome.Errors.ActionNotPermitted;

    void setAlarm(SmartHome.Interfaces.DailySchedule schedule, com.zeroc.Ice.Current current)
        throws SmartHome.Errors.ActionNotPermitted;

    SmartHome.Interfaces.DailySchedule getAlarm(com.zeroc.Ice.Current current)
        throws SmartHome.Errors.ActionNotPermitted;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Detectors::MoveDetector",
        "::Ice::Object",
        "::Interfaces::Detector",
        "::Interfaces::SmartDevice"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Detectors::MoveDetector";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_motionDetected(MoveDetector obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        boolean ret = obj.motionDetected(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_activateAlarm(MoveDetector obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        obj.activateAlarm(current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_deactivateAlarm(MoveDetector obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        obj.deactivateAlarm(current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_setAlarm(MoveDetector obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        SmartHome.Interfaces.DailySchedule iceP_schedule;
        iceP_schedule = SmartHome.Interfaces.DailySchedule.ice_read(istr);
        inS.endReadParams();
        obj.setAlarm(iceP_schedule, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getAlarm(MoveDetector obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        SmartHome.Interfaces.DailySchedule ret = obj.getAlarm(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        SmartHome.Interfaces.DailySchedule.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "activateAlarm",
        "changeMode",
        "deactivateAlarm",
        "getAlarm",
        "getLocation",
        "getMode",
        "getSensitivityLevel",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "motionDetected",
        "notify",
        "setAlarm",
        "setLocation",
        "setSensitivityLevel"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_activateAlarm(this, in, current);
            }
            case 1:
            {
                return SmartHome.Interfaces.SmartDevice._iceD_changeMode(this, in, current);
            }
            case 2:
            {
                return _iceD_deactivateAlarm(this, in, current);
            }
            case 3:
            {
                return _iceD_getAlarm(this, in, current);
            }
            case 4:
            {
                return SmartHome.Interfaces.Detector._iceD_getLocation(this, in, current);
            }
            case 5:
            {
                return SmartHome.Interfaces.SmartDevice._iceD_getMode(this, in, current);
            }
            case 6:
            {
                return SmartHome.Interfaces.Detector._iceD_getSensitivityLevel(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 9:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 10:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 11:
            {
                return _iceD_motionDetected(this, in, current);
            }
            case 12:
            {
                return SmartHome.Interfaces.SmartDevice._iceD_notify(this, in, current);
            }
            case 13:
            {
                return _iceD_setAlarm(this, in, current);
            }
            case 14:
            {
                return SmartHome.Interfaces.Detector._iceD_setLocation(this, in, current);
            }
            case 15:
            {
                return SmartHome.Interfaces.Detector._iceD_setSensitivityLevel(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
