//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `SmartHome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome.Errors;

public class ActionNotPermitted extends com.zeroc.Ice.UserException
{
    public ActionNotPermitted()
    {
    }

    public ActionNotPermitted(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::Errors::ActionNotPermitted";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Errors::ActionNotPermitted", -1, true);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -1033643412296267995L;
}
